site_name: Norse IoT Club - Wiki
theme:
  name: readthedocs
  palette:
    scheme: slate
  icon: assets/favicon.png
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.integrate
extra_css:
  - stylesheets/iot.css
extra_javascript:
  - javascripts/removeWatermark.js
markdown_extensions:
  - abbr
  - sane_lists
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences 

